import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect } from 'react';
import styles from "../../styles/Home.module.css"
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();

	useEffect(() => {
		const checkLogin = async () => {
			try {
				const cognitoUser = await Auth.currentAuthenticatedUser();
				const currentSession = await Auth.currentSession();
				//console.log({ currentSession, cognitoUser });
				if (cognitoUser) {
					router.push(`/dashboard`);
				}
			} catch (err) {
				//console.log('err', err);
				router.push('/authentication/login');
			}
		};
		checkLogin();
	}, []);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
				<h1 className={styles.title}>{/* Welcome to <a href="https://nextjs.org">Home page!</a> */}</h1>
			</main>
    </div>
  )
}
